# Ubuntu 15.04 with Java 8 installed
 
FROM ubuntu:15.04
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y  software-properties-common && \
    add-apt-repository ppa:webupd8team/java -y && \
    apt-get update && \
    echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections && \
    apt-get install -y oracle-java8-installer && \
	apt-get install oracle-java8-set-default && \
	apt-get install unzip && \
    apt-get clean
	
ADD box.options-0.1.zip .
RUN unzip -q box.options-0.1.zip && \
    rm box.options-0.1.zip && \
    mv box.options-* box.options && \
    chmod +x box.options/bin/start.sh && \
    chmod +x box.options/bin/stop.sh && \
    sed -i -e 's/\r$//' box.options/bin/start.sh && \
    sed -i -e 's/\r$//' box.options/bin/stop.sh

EXPOSE 8888

ENTRYPOINT ["/box.options/bin/start.sh"]
CMD ["--console"]